# Generated by Django 6.1.1 on 2026-09-25 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.CharField(help_text="e.g. 'Module 01'", max_length=30)),
                ('order', models.PositiveIntegerField(default=1, help_text='Sort order within the course')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('note_type', models.CharField(choices=[('Lecture Handout', 'Lecture Handout'), ('Cheatsheet', 'Cheatsheet'), ('Architecture Guide', 'Architecture Guide'), ('Exam Prep', 'Exam Prep')], default='Lecture Handout', max_length=30)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('file_size_mb', models.DecimalField(decimal_places=1, default=1.0, max_digits=6)),
                ('edition', models.CharField(blank=True, help_text="e.g. 'Fall 2026 Edition'", max_length=60)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='course_notes/')),
                ('topics', models.JSONField(blank=True, default=list, help_text='List of short topic tags, e.g. ["OOP", "Generators"]')),
                ('summary', models.TextField(blank=True)),
                ('table_of_contents', models.JSONField(blank=True, default=list, help_text='List of TOC line strings')),
                ('key_takeaways', models.JSONField(blank=True, default=list, help_text='List of revision bullet strings')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.course')),
                ('instructor', models.ForeignKey(blank=True, help_text='Defaults to the course instructor if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to='courses.instructor')),
            ],
            options={
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NoteCodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=30)),
                ('code', models.TextField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='notes.coursenote')),
            ],
            options={
                'ordering': ['note', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NoteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('heading', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('bullet_points', models.JSONField(blank=True, default=list)),
                ('key_highlight', models.CharField(blank=True, max_length=300)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='notes.coursenote')),
            ],
            options={
                'ordering': ['note', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NoteBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='notes.coursenote')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'note')},
            },
        ),
    ]
