# Generated by Django 4.2 on 2026-09-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_studentprofile_address_studentprofile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
    ]
