# Generated by Django 6.1.1 on 2026-09-24 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_studentprofile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='career_goal',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avatar_initials',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='headline',
            field=models.CharField(blank=True, help_text="e.g. 'Aspiring Full-Stack Developer'", max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
