# Generated by Django 5.2.17 on 2026-10-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='achievement',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='progress_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='achievement',
            name='requirement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='tier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='achievement',
            name='unlocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='unlocked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
